### ISSUE TITLE
Does the invalidation not show up in the AWS admin UI?

### ISSUE THREAD

**Issue by chrishawn** [confyio/gulp-cloudfront-invalidate#2]
i see an output like Cloudfront invalidation created: I2WHH1PTRYY4DX but i don't see that reflected anywhere in the UI.. am i missing a setting or do they just not show there when done through gulp?

**Comment by pksunkara** [comment]
If it says invalidation is created, then AWS did it. I remember the invalidation being shown in the UI. Maybe it takes a bit of time? Might be a cache issue on amazon side.

**Comment by chrishawn** [comment]
it does not invalidate paths: ['/*'] doesn't show in ui, files still not invalidated... are there special IAM permissions needed?

**Comment by pksunkara** [comment]
@chrishawn This just directly calls the AWS SDK, so I have no idea. http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/UsingWithIAM.html

**Comment by pksunkara** [comment]
@chrishawn Any update on this?

**Comment by chrishawn** [comment]
it seems to invalidate the first cloudfront entry always, regardless of what distribution id i give it.

**Comment by pksunkara** [comment]
@chrishawn Can you give me the sample gulp code you are using? And can you describe what exactly you think is wrong? I am afraid I can't understand what you mean by your previous comment.

**Comment by chrishawn** [comment]
```
gulp.task('publish-dev-sites', [], function(){
    awsSettings.params.Bucket="site/dev";
    cfProviders=cfSettings;
    cfProviders.distribution='ERORMEQD3QQQQ';
    cfGroups=cfSettings;
    cfGroups.distribution='E1JKYAL3TXXXX';
    var publisher = awspublish.create(awsSettings);
    return gulp.src('./site/**/*')
        .pipe(parallelize(publisher.publish(), 20))
        .pipe(awspublish.reporter())
        .pipe(cloudfront(cfProviders))
        .pipe(cloudfront(cfGroups))
        .on('error', gulputil.log);
});
```

so if ERORMEQD3QQQQ is not the first entry in cloudfront... it won't get the invalidation, the one that shows first in cloudfront will always get the invalidation even if it id is not specified here.. almost like it ignores the .distribution property

**Comment by pksunkara** [comment]
Ah ha. So, you are trying to invalidate 2 different distributions. Right?

**Comment by pksunkara** [comment]
Can you try invalidating the `ERORMEQD3QQQQ` while removing the line `.pipe(cloudfront(cfGroups)`?

``` js
gulp.task('publish-dev-sites', [], function(){
    awsSettings.params.Bucket="site/dev";
    cfProviders=cfSettings;
    cfProviders.distribution='ERORMEQD3QQQQ';
    var publisher = awspublish.create(awsSettings);
    return gulp.src('./site/**/*')
        .pipe(parallelize(publisher.publish(), 20))
        .pipe(awspublish.reporter())
        .pipe(cloudfront(cfProviders))
        .on('error', gulputil.log);
});
```
